title: Yongming Li
theme: jekyll-theme-minimal
logo: rsz_1img_20160425_235119.jpg
email: liyo0008@tamu.edu
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
   
favicon: true
github: [metadata]
google_analytics: G-6Y5EWX3Z61
